# Generated by Django 5.2.2 on 2025-06-08 05:39

import functools
import utils.upload_file
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.ImageField(upload_to=functools.partial(utils.upload_file.upload_to_timestamp, *('banners/',), **{}))),
            ],
            options={
                'db_table': 'banners',
            },
        ),
    ]
