# Generated by Django 5.2.2 on 2025-06-08 05:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companys', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('5e6f6eae-451e-48ea-bb2e-2ba96de81d08'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('salary', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=100)),
                ('requirements', models.TextField()),
                ('description', models.TextField()),
                ('is_remote', models.BooleanField(default=False)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('is_open', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companys.company')),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
    ]
